// @ts-check
/**
 * Token codegen: tokens.ts (source of truth) → RN theme object + CSS variables.
 * Same input, two platform outputs — this is what keeps RN and Tauri designs
 * consistent by construction rather than by discipline.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { colors, spacing, radii, typography, motion, breakpoints } from './tokens.ts';

const HERE = dirname(fileURLToPath(import.meta.url)); // .../design-tokens/src
const PKG = dirname(HERE); // .../design-tokens
const RN_OUT = join(HERE, 'generated', 'rn.ts');
const CSS_OUT = join(PKG, 'dist', 'tokens.css');

mkdirSync(dirname(RN_OUT), { recursive: true });
mkdirSync(dirname(CSS_OUT), { recursive: true });

/* ---------- CSS custom properties: --eagle-<group>-<name> ---------- */

const cssEntries = [
  ...Object.entries(colors).map(([k, v]) => [`--eagle-color-${kebab(k)}`, v]),
  ...Object.entries(spacing).map(([k, v]) => [`--eagle-space-${kebab(k)}`, `${v}px`]),
  ...Object.entries(radii).map(([k, v]) => [`--eagle-radius-${kebab(k)}`, `${v}px`]),
  ...Object.entries(typography).map(([k, v]) => [`--eagle-typo-${kebab(k)}`, String(v)]),
  ...Object.entries(motion).map(([k, v]) => [`--eagle-motion-${kebab(k)}`, `${v}ms`]),
  ...Object.entries(breakpoints).map(([k, v]) => [`--eagle-bp-${kebab(k)}`, `${v}px`]),
];

const css = `/* Generated by build.mjs — DO NOT EDIT. Source: tokens.ts */
:root {
${cssEntries.map(([prop, value]) => `  ${prop}: ${value};`).join('\n')}
}
`;
writeFileSync(CSS_OUT, css);
console.log(`wrote ${CSS_OUT} (${cssEntries.length} custom properties)`);

/* ---------- RN theme: nested objects, StyleSheet-ready ---------- */

const rn = `// Generated by build.mjs — DO NOT EDIT. Source: tokens.ts
export const theme = {
  colors: ${JSON.stringify(colors, null, 2)},
  spacing: ${JSON.stringify(spacing, null, 2)},
  radii: ${JSON.stringify(radii, null, 2)},
  typography: ${JSON.stringify(typography, null, 2)},
  motion: ${JSON.stringify(motion, null, 2)},
  breakpoints: ${JSON.stringify(breakpoints, null, 2)},
} as const;

export type Theme = typeof theme;
`;
writeFileSync(RN_OUT, rn);
console.log(`wrote ${RN_OUT}`);

function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
