import { chromium } from '/_home/.npm/_npx/226752580240d182/node_modules/playwright/index.mjs';
const browser = await chromium.launch({ executablePath: '/_home/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', e => errors.push('PAGE: ' + e.message.slice(0, 150)));
page.on('requestfailed', r => errors.push('REQFAIL: ' + r.url().slice(0, 130) + ' ' + (r.failure()?.errorText ?? '')));
page.on('response', r => { if (r.status() >= 400 && r.url().includes('jf.onemue.cn')) errors.push('HTTP' + r.status() + ': ' + r.url().slice(0, 130)); });
await page.goto('http://localhost:1420/player/jfv%3Aa60540f4a285162480779c56c23c27e8', { waitUntil: 'networkidle' }).catch(e => console.log('goto:', e.message.slice(0, 80)));
await page.waitForTimeout(8000);
console.log('url:', page.url());
console.log('body:', JSON.stringify((await page.evaluate(() => document.body.innerText)).slice(0, 150)));
const video = await page.locator('video').count();
console.log('video:', video);
if (video) console.log('vstate:', JSON.stringify(await page.evaluate(() => { const v = document.querySelector('video'); return { ready: v.readyState, w: v.videoWidth, err: v.error?.code, msg: v.error?.message?.slice(0, 80) }; })));
console.log('errors:', errors.length ? errors.slice(0, 6) : 'none');
await browser.close();
