import { chromium } from '/_home/.npm/_npx/226752580240d182/node_modules/playwright/index.mjs';
const browser = await chromium.launch({ executablePath: '/_home/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message.slice(0, 150)));
await page.goto('http://localhost:1420/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1200);
await page.getByText('⚙︎').click();
await page.waitForTimeout(500);
await page.getByText('M3U Tuner').last().click();
await page.waitForTimeout(400);
await page.getByPlaceholder('http://example.com/playlist.m3u').fill('https://iptv-org.github.io/iptv/countries/cn.m3u');
await page.getByText('添加', { exact: true }).click();
await page.waitForTimeout(12000);
const text = await page.evaluate(() => document.body.innerText);
const channelCount = await page.evaluate(() => Array.from(document.querySelectorAll('div,span')).filter(e => e.childElementCount === 0 && e.textContent.length > 3 && e.getBoundingClientRect().height > 10).length);
console.log('body sample:', JSON.stringify(text.slice(0, 300)));
console.log('pageerrors:', errors.length ? errors.slice(0,3) : 'none');
await browser.close();
