import { chromium } from '/_home/.npm/_npx/226752580240d182/node_modules/playwright/index.mjs';
const browser = await chromium.launch({ executablePath: '/_home/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message.slice(0, 120)));
await page.goto('http://localhost:1420/', { waitUntil: 'domcontentloaded' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'networkidle' });
await page.waitForTimeout(800);
await page.getByText('⚙︎').click();
await page.waitForTimeout(400);
await page.getByText('HDHomeRun').last().click();
await page.waitForTimeout(300);
await page.getByPlaceholder('http://192.168.1.50').fill('http://127.0.0.1:1954');
await page.getByText('添加', { exact: true }).click();
await page.waitForTimeout(3500);
// row text is "1.1 · CCTV-1 综合"
const row = page.getByText('1.1 · CCTV-1 综合').first();
console.log('row found:', await row.isVisible().catch(() => false));
await row.click({ timeout: 6000 });
await page.waitForTimeout(3000);
console.log('video mounted:', (await page.locator('video').count()) === 1);
console.log('pageerrors:', errors.length ? errors : 'none');
await browser.close();
