import { chromium } from '/_home/.npm/_npx/226752580240d182/node_modules/playwright/index.mjs';
const browser = await chromium.launch({ executablePath: '/_home/.cache/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-linux64/chrome-headless-shell', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message.slice(0, 120)));
await page.goto('http://localhost:1420/', { waitUntil: 'domcontentloaded' });
await page.evaluate(() => localStorage.clear());
await page.reload({ waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
const rowsVisible = await page.evaluate(() => document.body.innerText.includes('Anhui TV') || document.body.innerText.includes('CCTV'));
console.log('1. rows visible during health check:', rowsVisible);
await page.getByText('Anhui TV', { exact: true }).first().click({ timeout: 8000 });
await page.waitForTimeout(5000);
const hasVideo = await page.locator('video').count();
const bodyText = (await page.evaluate(() => document.body.innerText)).slice(0, 150);
const videoReady = hasVideo ? await page.evaluate(() => { const v = document.querySelector('video'); return { readyState: v.readyState, w: v.videoWidth, h: v.videoHeight, err: v.error?.code }; }) : null;
console.log('2. video:', hasVideo, '| state:', JSON.stringify(videoReady), '| text:', JSON.stringify(bodyText.slice(0, 80)));
console.log('3. pageerrors:', errors.length ? errors : 'none');
await browser.close();
